-- Run in the existing Supabase SQL editor if these tables are not already present.
create table if not exists strategy_rules (
  id bigint generated by default as identity primary key,
  source text,
  file_name text,
  content text not null,
  rule_text text not null,
  created_at timestamptz not null default now()
);
create table if not exists audited_trades (
  id bigint generated by default as identity primary key,
  owner_open_id text,
  raw_signal text not null,
  asset text not null,
  timeframe text,
  direction text not null,
  entry numeric,
  stop_loss numeric,
  take_profit numeric,
  verdict text not null check (verdict in ('TRADE APPROVED', 'TRADE DENIED')),
  confidence numeric,
  adjustments text,
  rationale text,
  created_at timestamptz not null default now()
);
create table if not exists trade_signals (
  id bigint generated by default as identity primary key,
  asset text not null,
  timeframe text not null,
  direction text not null,
  entry numeric not null,
  stop_loss numeric not null,
  take_profit numeric not null,
  risk_reward text,
  confidence numeric,
  rationale text,
  status text not null default 'OPEN',
  outcome text check (outcome in ('WIN', 'LOSS')),
  created_at timestamptz not null default now()
);
-- lessons_learned already exists in the user's Supabase project with columns:
-- id int8, asset_pair text, lesson_learned text, embedding vector, created_at timestamptz.
-- Do not recreate or alter it here; the application writes to those existing columns.
