import { BookOpen, RefreshCw } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { RuleImporter } from "@/components/RuleImporter";
import { trpc } from "@/lib/trpc";

export default function StrategyRules() {
  const rules = trpc.rules.list.useQuery();
  return <div className="mx-auto max-w-6xl space-y-6 py-4"><div><Badge className="border border-amber-300/20 bg-amber-300/10 text-amber-200">RULES / 04</Badge><h1 className="mt-3 text-3xl font-semibold text-white">Your strategy memory.</h1><p className="mt-2 max-w-2xl text-slate-400">Append new rules as your playbook evolves. Existing records are never overwritten.</p></div><div className="grid gap-6 lg:grid-cols-[.72fr_1.28fr]"><Card className="border-slate-800 bg-slate-900/70"><CardHeader><CardTitle className="text-slate-100">Add rules</CardTitle></CardHeader><CardContent><RuleImporter onComplete={() => rules.refetch()} /></CardContent></Card><Card className="border-slate-800 bg-slate-900/70"><CardHeader><CardTitle className="flex items-center justify-between text-slate-100"><span className="flex items-center gap-2"><BookOpen className="h-4 w-4 text-cyan-300" />Ingested rules</span><button onClick={() => rules.refetch()} className="rounded-md p-2 text-slate-400 hover:bg-slate-800 hover:text-white" aria-label="Refresh rules"><RefreshCw className="h-4 w-4" /></button></CardTitle></CardHeader><CardContent className="space-y-3">{rules.isLoading ? <p className="text-sm text-slate-500">Loading strategy memory…</p> : rules.isError ? <p className="text-sm text-amber-300">Strategy memory could not be loaded. Check the Supabase table and try refresh.</p> : rules.data?.length ? rules.data.map((row, index) => <div key={String(row.id ?? index)} className="rounded-xl border border-slate-800 bg-slate-950/60 p-4"><div className="flex items-center justify-between gap-3"><p className="text-sm font-medium text-slate-200">{String(row.file_name ?? row.source ?? `Rule block ${index + 1}`)}</p><span className="text-xs text-slate-600">{row.created_at ? new Date(String(row.created_at)).toLocaleDateString() : ""}</span></div><p className="mt-2 line-clamp-3 whitespace-pre-wrap text-sm leading-6 text-slate-400">{String(row.rule_text ?? row.content ?? row.text ?? "")}</p></div>) : <div className="rounded-xl border border-dashed border-slate-800 p-8 text-center text-sm text-slate-500">No rules ingested yet. Add your first rule block to activate grounded audits.</div>}</CardContent></Card></div></div>;
}
